//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.11 at 05:49:42 PM CET 
//


package net.atomique.ksar.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.atomique.ksar.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.atomique.ksar.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfiG }
     * 
     */
    public ConfiG createConfiG() {
        return new ConfiG();
    }

    /**
     * Create an instance of {@link Colors }
     * 
     */
    public Colors createColors() {
        return new Colors();
    }

    /**
     * Create an instance of {@link OS }
     * 
     */
    public OS createOS() {
        return new OS();
    }

    /**
     * Create an instance of {@link Stack }
     * 
     */
    public Stack createStack() {
        return new Stack();
    }

    /**
     * Create an instance of {@link Stat }
     * 
     */
    public Stat createStat() {
        return new Stat();
    }

    /**
     * Create an instance of {@link Format }
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link Itemcolor }
     * 
     */
    public Itemcolor createItemcolor() {
        return new Itemcolor();
    }

    /**
     * Create an instance of {@link Plot }
     * 
     */
    public Plot createPlot() {
        return new Plot();
    }

    /**
     * Create an instance of {@link OSType }
     * 
     */
    public OSType createOSType() {
        return new OSType();
    }

    /**
     * Create an instance of {@link Graph }
     * 
     */
    public Graph createGraph() {
        return new Graph();
    }

}
